default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
exclude: |
  (?x)(
      ^.*.svg|
      ^assets/|
      ^src/ccbr_tools/templates/mkdocs-fnl/docs/custom-overrides/|
      ^tests/data/
   )
repos:
  - repo: https://github.com/CCBR/Tools
    rev: v0.5.1
    hooks:
      - id: detect-absolute-paths
        exclude: |
          (?x)^(
              .gitignore|
              .gitattributes|
              .*.gitignore|
              .*.diff|
              .*action.yml|
              examples/.*|
              docs/.*|
              tests/.*|
              templates/|
              src/ccbr_tools/pipeline/.*
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  # spell check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          [
            -I,
            .github/WORDLIST,
            --skip,
            "*human_mouse_homolog_lookup.txt,*.rpt",
          ]
  # Quarto formatting
  # - repo: https://github.com/jolars/panache
  #   rev: v2.13.0
  #   hooks:
  #     - id: panache-format
  #     - id: panache-lint
  # Python formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  # general linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
  # enforce commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
