# see: https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "CCBR Tools"
  site-url: https://ccbr.github.io/Tools
  repo-url: https://github.com/CCBR/Tools
  repo-actions: [edit, issue]
  sidebar:
    - id: reference
      contents: "_sidebar.yml"
  navbar:
    left:
      - text: Home
        href: index.md
      - text: Reference
        href: reference/index.qmd
    right:
      - text: Changelog
        href: CHANGELOG.md
      - text: Contributing
        href: CONTRIBUTING.md
      - icon: github
        href: https://github.com/CCBR/Tools
        aria-label: CCBR/Tools GitHub
  page-footer:
    left: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  package: ccbr_tools
  parser: google
  sidebar: _sidebar.yml
  sections:
    - title: Modules
      contents:
        - jobby
        - peek
        - pipeline
        - pkg_util
        - shell

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources: {}

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
