# see: https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "CCBR Tools"
  site-url: https://ccbr.github.io/Tools
  repo-url: https://github.com/CCBR/Tools
  repo-actions: [edit, issue]
  sidebar:
    - id: reference
      style: docked
      contents: "_sidebar.yml"
    - id: docs
      title: Docs
      style: docked
      contents:
        - text: API Reference
          href: reference/index.qmd
        - text: Changelog
          href: CHANGELOG.md
        - text: Contributing
          href: CONTRIBUTING.md
        - href: contributors.qmd

  navbar:
    search: true
    left:
      - text: Home
        href: index.md
    right:
      - sidebar:docs
      - icon: github
        href: https://github.com/CCBR/Tools
        aria-label: CCBR/Tools GitHub

  page-footer:
    left: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  package: ccbr_tools
  parser: google
  render_interlinks: true
  sidebar: _sidebar.yml
  title: "API Reference"
  sections:
    - title: Modules
      contents:
        - github
        - jobby
        - peek
        - pipeline.cache
        - pipeline.hpc
        - pipeline.nextflow
        - pipeline.util
        - pkg_util
        - shell
        - templates
    - title: Legacy tools
      contents:
        - GSEA.deg2gs
        - GSEA.multitext2excel
        - GSEA.ncbr_huse
        - gb2gtf
        - homologfinder.hf
        - intersect
        - jobinfo

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    # ccbr_actions:
    #   url: https://ccbr.github.io/actions/reference
    # ccbr_tools:
    #   url: https://ccbr.github.io/Tools/reference

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
