# see: https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "CCBR Tools"
  site-url: https://ccbr.github.io/Tools
  repo-url: https://github.com/CCBR/Tools
  repo-actions: [edit, issue]
  sidebar:
    - id: docs
      title: Docs
      style: docked
      contents:
        - text: Home
          href: index.qmd
        - section: Usage
          contents:
            - href: cli.qmd
            - href: scripts.qmd
            - text: Python API reference
              href: reference/index.qmd
              contents: "_sidebar.yml"
        - section: Project information
          contents:
            - text: Citation
              href: cite.qmd
            - text: Contributing
              href: CONTRIBUTING.md
            - href: contributors.qmd
            - text: License
              href: LICENSE.md
            - text: Changelog
              href: CHANGELOG.md

  navbar:
    search: true
    right:
      - sidebar:docs
      - icon: github
        href: https://github.com/CCBR/Tools
        aria-label: CCBR/Tools GitHub

  page-footer:
    background: black
    foreground: white
    left: |
      [![](/_extensions/fnl/fnl-logo-dark.png){height=70px}](https://frederick.cancer.gov/research/science-areas/bioinformatics-and-computational-science/advanced-biomedical-computational-science)
    center: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  package: ccbr_tools
  parser: google
  render_interlinks: true
  sidebar: _sidebar.yml
  title: "API Reference"
  sections:
    - title: Main modules
      contents:
        - github
        - pkg_util
        - pipeline
        - send_email
        - shell
        - templates
    - title: Pipeline utilities
      contents:
        - pipeline.cache
        - pipeline.hpc
        - pipeline.nextflow
        - pipeline.util
    - title: Legacy tools
      contents:
        - GSEA.deg2gs
        - GSEA.multitext2excel
        - GSEA.ncbr_huse
        - gb2gtf
        - homologfinder.hf
        - intersect
        - jobinfo
        - jobby
        - peek

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    # ccbr_actions:
    #   url: https://ccbr.github.io/actions/reference
    # ccbr_tools:
    #   url: https://ccbr.github.io/Tools/reference

execute:
  freeze: auto
  eval: true
  echo: true

format: fnl-html
