name: black

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: format
        uses: psf/black@stable
        with:
          options: "--verbose"
          use_pyproject: true
      - name: commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: 🤖 black formatting" && git push || echo "nothing to commit"
